version: "3.7"

services:
  
  db:
    image: palchukovsky/wallet/db
    restart: always
    environment:
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: WaLlEtSeCrEtPaSsWoRd4
    ports:
      - 5432:5432

  dbadmin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080